package com.may18;
import java.util.*;
public class exceptionexp1 {
	public static void main(String[] args) {
		try{
			Scanner ob=new Scanner(System.in);
			System.out.println("enter 2 numbers");
			int a =ob.nextInt();
			int b =ob.nextInt();
			int c=a/b;
			System.out.println("result is "+c);
		}
			catch(Exception ae)
			{
				System.out.println("error i s"+ae);
			
				}
			System.out.println("program continues");
		}
	
	}
